name:                multtable
version:             0.1
github:              "puripuri2100/multtable"
license:             MIT
author:              "puripuri2100"
maintainer:          "puripuri2100@gmail.com"
copyright:           "2019 puripuri2100"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/puripuri2100/multtable#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  multtable-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multtable

tests:
  multtable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multtable
